name: unpub_web
description: A web app that uses AngularDart Components
version: 1.0.0
author: Rongjian Zhang <pd4d10@gmail.com>
publish_to: none

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  angular: ^5.3.1
  angular_router: ^2.0.0-alpha+22
  angular_forms: ^2.1.2
  markdown: ^2.1.3
  unpub:
    path: ../unpub

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.8.1
  build_test: ^0.10.3
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
